[package]
name = "bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
log = "0.4.21"
serde = "1.0.197"
futures = "0.3.30"
thiserror = "1.0.58"
serde_json = "1.0.114"
derive_more = "0.99.17"
derive-getters = "0.3.0"
bitcoin = { version = "0.31.1", features = [ "serde" ] }
